on:
    push:
        branches:
            - main
            - dev
    workflow_dispatch:  

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/dev' && 'dev' }}

    env:
      TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
      TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_domain: ${{ secrets.DOMAIN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TF_VAR_env: ${{ secrets.ENV}}
      TF_VAR_email: ${{ secrets.EMAIL}}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.TF_VAR_gcp_credentials }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform Changes
        run: terraform plan 

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve      
